apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogImppdHNpIgogIHN0YXRpY19jb25maWdzOgogIC0gdGFyZ2V0czogWyJleHBvcnRlci5qaXRzaTo4MDgwIl0=
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
