apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: default-backend
  name: default-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      containers:
      - image: hub.vngcloud.tech/public/default-backend:0.1
        name: default-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: default-backend
  name: default-backend
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: default-backend