apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haproxy
  namespace: ingress-nginx
  labels:
    k8s-app: haproxy
spec:
  selector:
    matchLabels:
      name: haproxy
  template:
    metadata:
      labels:
        name: haproxy
    spec:
      hostNetwork: true
      containers:
      - name: haproxy
        image: hub.vngcloud.tech/public/haproxy:2.0.14
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/haproxy
          readOnly: true
        - name: log
          mountPath: /dev/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: haproxy
      - name: log
        hostPath: 
          path: /dev/log