apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: haproxy
  name: haproxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: haproxy
  template:
    metadata:
      labels:
        k8s-app: haproxy
    spec:
      containers:
        - name: haproxy
          image: registry.vngcloud.vn/marketplace/haproxy-web:4384
          envFrom:
          - configMapRef:
              name: env
          volumeMounts:
          - mountPath: /config
            name: web

      volumes:
      - name: config
        hostPath:
          path: /opt/haproxy
          type: DirectoryOrCreate

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haproxy
  namespace: ingress-nginx
  labels:
    k8s-app: haproxy
spec:
  selector:
    matchLabels:
      name: haproxy
  template:
    metadata:
      labels:
        name: haproxy
    spec:
      containers:
      - name: haproxy
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers