apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: jitsi
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    nodePort: 32080
  - name: "https"
    port: 443
    targetPort: 443
    nodePort: 32443
  selector:
    k8s-app: jitsi
  type: NodePort
---
 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: jitsi
   namespace: jitsi
   annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
 spec:
  rules:
  - host: meet.vngcloud.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: https
