apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: jitsi
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      containers:
        - name: web
          image: registry.vngcloud.vn/marketplace/jitsi-web:4384
          envFrom:
          - configMapRef:
              name: env
          volumeMounts:
          - mountPath: /config
            name: web
          - mountPath: /etc/letsencrypt
            name: letsencrypt
          - mountPath: /usr/share/jitsi-meet/transcripts
            name: transcripts
          ports:
          - containerPort: 80
          - containerPort: 443  
        - name: prosody
          image: registry.vngcloud.vn/marketplace/jitsi-prosody:4384
          envFrom:
          - configMapRef:
              name: env
          volumeMounts:
          - mountPath: /config
            name: prosody
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "prosodyctl --config=/config/prosody.cfg.lua register $XMPP_USER $XMPP_AUTH_DOMAIN $XMPP_PW || echo FAIL_CREATE_USER_EXPORTER"]

        - name: jicofo
          image: registry.vngcloud.vn/marketplace/jitsi-jicofo:4384
          envFrom:
          - configMapRef:
              name: env
          volumeMounts:
          - mountPath: /config
            name: jicofo

        - name: jvb
          image: registry.vngcloud.vn/marketplace/jitsi-jvb:4384
          envFrom:
          - configMapRef:
              name: env
          volumeMounts:
          - mountPath: /config
            name: jvb

        - name: jibri
          image: registry.vngcloud.vn/marketplace/jitsi-jibri:4384
          securityContext:
            privileged: true
            capabilities: 
              add: ["SYS_ADMIN", "NET_BIND_SERVICE"]
          envFrom:
          - configMapRef:
              name: env
          env:
          - name: DISPLAY
            value: ":0"
          volumeMounts:
          - mountPath: /config
            name: jibri
          - mountPath: /dev/snd
            name: dev-snd
          - mountPath: /dev/shm
            name: dev-shm
        
        - name: exporter
          image: registry.vngcloud.vn/marketplace/jitsi-exporter:v0.0.4
          envFrom:
          - configMapRef:
              name: env
          ports:
          - containerPort: 8080

      volumes:
      - name: web
        hostPath:
          path: /opt/jitsi-meet-cfg/web
          type: DirectoryOrCreate
      - name: letsencrypt
        hostPath:
          path: /opt/jitsi-meet-cfg/web/letsencrypt
          type: DirectoryOrCreate
      - name: transcripts
        hostPath:
          path: /opt/jitsi-meet-cfg/transcripts
          type: DirectoryOrCreate
      - name: prosody
        hostPath:
          path: /opt/jitsi-meet-cfg/prosody
          type: DirectoryOrCreate
      - name: jicofo
        hostPath:
          path: /opt/jitsi-meet-cfg/jicofo
          type: DirectoryOrCreate
      - name: jvb
        hostPath:
          path: /opt/jitsi-meet-cfg/jvb
          type: DirectoryOrCreate
      - name: jibri
        hostPath:
          path: /opt/jitsi-meet-cfg/jibri
          type: DirectoryOrCreate
      - name: dev-snd
        hostPath:
          path: /dev/snd
      - name: dev-shm
        hostPath:
          path: /dev/shm