apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
  namespace: jitsi
  annotations: 
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: jitsi
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      containers:
        - name: web
          image: registry.vngcloud.vn/marketplace/jitsi-web:4384
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: JICOFO_AUTH_USER
              value: focus
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: XMPP_BOSH_URL_BASE
              value: http://127.0.0.1:5280
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
          volumeMounts:
          - mountPath: /config
            name: web
        - name: prosody
          image: registry.vngcloud.vn/marketplace/jitsi-prosody:4384
          env:
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-secret
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-secret
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-secret
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
          volumeMounts:
          - mountPath: /config
            name: prosody
        - name: jicofo
          image: registry.vngcloud.vn/marketplace/jitsi-jicofo:4384
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-secret
                  key: JICOFO_COMPONENT_SECRET
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-secret
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
          volumeMounts:
          - mountPath: /config
            name: jicofo
        - name: jvb
          image: registry.vngcloud.vn/marketplace/jitsi-jvb:4384
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: DOCKER_HOST_ADDRESS
              value: localhost
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JVB_STUN_SERVERS
              value: meet-jit-si-turnrelay.jitsi.net:443
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_PORT
              value: "31000"
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-secret
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-secret
                  key: JICOFO_AUTH_PASSWORD
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: TZ
              value: Asia/Ho_Chi_Minh
          volumeMounts:
          - mountPath: /config
            name: jvb
      volumes:
      - name: web
        hostPath:
          path: /opt/jitsi-meet-cfg/web
          type: DirectoryOrCreate
      - name: letsencrypt
        hostPath:
          path: /opt/jitsi-meet-cfg/web/letsencrypt
          type: DirectoryOrCreate
      - name: transcripts
        hostPath:
          path: /opt/jitsi-meet-cfg/transcripts
          type: DirectoryOrCreate
      - name: prosody
        hostPath:
          path: /opt/jitsi-meet-cfg/prosody
          type: DirectoryOrCreate
      - name: jicofo
        hostPath:
          path: /opt/jitsi-meet-cfg/jicofo
          type: DirectoryOrCreate
      - name: jvb
        hostPath:
          path: /opt/jitsi-meet-cfg/jvb
          type: DirectoryOrCreate
