apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: jitsi
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      containers:
        - name: web
          image: registry.vngcloud.vn/marketplace/jitsi-web:4384
          envFrom:
          - configMapRef:
              name: env
          volumeMounts:
          - mountPath: /config
            name: web
          - mountPath: /etc/letsencrypt
            name: letsencrypt
          - mountPath: /usr/share/jitsi-meet/transcripts
            name: transcripts
          ports:
          - containerPort: 80
          - containerPort: 443  
        - name: prosody
          image: registry.vngcloud.vn/marketplace/jitsi-prosody:4384
          envFrom:
          - configMapRef:
              name: env
          volumeMounts:
          - mountPath: /config
            name: prosody
        - name: jicofo
          image: registry.vngcloud.vn/marketplace/jitsi-jicofo:4384
          envFrom:
          - configMapRef:
              name: env
          volumeMounts:
          - mountPath: /config
            name: jicofo
        - name: jvb
          image: registry.vngcloud.vn/marketplace/jitsi-jvb:4384
          envFrom:
          - configMapRef:
              name: env
          volumeMounts:
          - mountPath: /config
            name: jvb
      volumes:
      - name: web
        hostPath:
          path: /opt/jitsi-meet-cfg/web
          type: DirectoryOrCreate
      - name: letsencrypt
        hostPath:
          path: /opt/jitsi-meet-cfg/web/letsencrypt
          type: DirectoryOrCreate
      - name: transcripts
        hostPath:
          path: /opt/jitsi-meet-cfg/transcripts
          type: DirectoryOrCreate
      - name: prosody
        hostPath:
          path: /opt/jitsi-meet-cfg/prosody
          type: DirectoryOrCreate
      - name: jicofo
        hostPath:
          path: /opt/jitsi-meet-cfg/jicofo
          type: DirectoryOrCreate
      - name: jvb
        hostPath:
          path: /opt/jitsi-meet-cfg/jvb
          type: DirectoryOrCreate