apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 31000
    protocol: UDP
    targetPort: 31000
    nodePort: 31000
    name: udp
  selector:
    k8s-app: jitsi
